## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

:

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN", "NAME"])

NameError: name 'application_df' is not defined

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = ['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
application_df["CLASSIFICATION"].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = application_df['CLASSIFICATION'].unique().tolist()
classifications_to_replace.remove('C1000')
classifications_to_replace.remove('C2000')
classifications_to_replace.remove('C1200')
classifications_to_replace.remove('C3000')
classifications_to_replace.remove('C2100')

print(classifications_to_replace)

['C2700', 'C7000', 'C7200', 'C1700', 'C4000', 'C7100', 'C2800', 'C6000', 'C1238', 'C5000', 'C7120', 'C1800', 'C4100', 'C1400', 'C1270', 'C2300', 'C8200', 'C1500', 'C7210', 'C1300', 'C1230', 'C1280', 'C1240', 'C2710', 'C2561', 'C1250', 'C8000', 'C1245', 'C1260', 'C1235', 'C1720', 'C1257', 'C4500', 'C2400', 'C8210', 'C1600', 'C1278', 'C1237', 'C4120', 'C2170', 'C1728', 'C1732', 'C2380', 'C1283', 'C1570', 'C2500', 'C1267', 'C3700', 'C1580', 'C2570', 'C1256', 'C1236', 'C1234', 'C1246', 'C2190', 'C4200', 'C0', 'C3200', 'C5200', 'C1370', 'C2600', 'C1248', 'C6100', 'C1820', 'C1900', 'C2150']

In [ ]:
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_dummies = pd.get_dummies(data=application_df, 
                                        columns=['APPLICATION_TYPE', 
                                                 'AFFILIATION', 
                                                 'CLASSIFICATION', 
                                                 'USE_CASE', 
                                                 'ORGANIZATION',
                                                 'INCOME_AMT',
                                                 'SPECIAL_CONSIDERATIONS'])

application_df_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [ ]:
# Split our preprocessed data into our features and target arrays
y = application_df_dummies['IS_SUCCESSFUL'].values
X = application_df_dummies.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  80
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.5695 - accuracy: 0.7214
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5542 - accuracy: 0.7292
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5517 - accuracy: 0.7320
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5500 - accuracy: 0.7311
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5489 - accuracy: 0.7316
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5483 - accuracy: 0.7312
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5472 - accuracy: 0.7334
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7329
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5461 - accuracy: 0.7344
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7341
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7350
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7346
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5442 - accuracy: 0.7353
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5438 - accuracy: 0.7360
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7348
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7361
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5427 - accuracy: 0.7366
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5424 - accuracy: 0.7363
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5420 - accuracy: 0.7362
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5421 - accuracy: 0.7368
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5416 - accuracy: 0.7374
Epoch 22/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7360
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5416 - accuracy: 0.7378
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7370
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5408 - accuracy: 0.7361
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7372
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5408 - accuracy: 0.7375
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7380
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7374
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7377
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7377
Epoch 32/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7379
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7371
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7391
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7388
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7380
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7380
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7388
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7372
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7382
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7379
Epoch 42/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7385
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7382
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7388
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7392
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7387
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5380 - accuracy: 0.7391
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7388
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7399
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7389
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7383
Epoch 52/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7393
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7383
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7392
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7389
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7376
Epoch 57/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7392
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7391
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7396
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7385
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5367 - accuracy: 0.7393
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7391
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7396
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7393
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5366 - accuracy: 0.7392
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5367 - accuracy: 0.7393
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7383
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7391
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5365 - accuracy: 0.7399
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5364 - accuracy: 0.7385
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5363 - accuracy: 0.7386
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5363 - accuracy: 0.7394
Epoch 73/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7393
Epoch 74/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7390
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7398
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7388
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5360 - accuracy: 0.7390
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7399
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7393
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7393
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7395
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5359 - accuracy: 0.7395
Epoch 83/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7399
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7399
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5355 - accuracy: 0.7398
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7397
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5355 - accuracy: 0.7394
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7395
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5355 - accuracy: 0.7400
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5355 - accuracy: 0.7387
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7401
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7396
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5351 - accuracy: 0.7402
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7400
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5354 - accuracy: 0.7397
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5350 - accuracy: 0.7399
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5347 - accuracy: 0.7396
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5352 - accuracy: 0.7396
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5346 - accuracy: 0.7397
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7404

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5570 - accuracy: 0.7273 - 455ms/epoch - 2ms/step
Loss: 0.5569981336593628, Accuracy: 0.7273469567298889

In [ ]:
import h5py

# Export our model to HDF5 file
nn.save("model.hdf5")

C:\Users\victo\AppData\Roaming\Python\Python311\site-packages\keras\src\engine\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(